---
title: "R Notebook"
output: html_notebook
---

```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
library(tidyverse)
library(readxl)
library(janitor)
options(scipen = 999, browser = "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe")
```



```{r message=FALSE, warning=FALSE}
library(scales)
#### FORMULA INPUT ASSUMPTIONS ###
cola_2017_18 <- 2.71
cola_2018_19 <- 3.26
ftes_growth_rate <- 0.55

#BASE ALLOCATION DOLLAR AMOUNTS
funds_available_for_distribution <- 6956349082 
funds_available_for_base_allocation <- funds_available_for_distribution*.7
funds_available_for_supp_allocation <- funds_available_for_distribution*.2
funds_available_for_succ_allocation_main <- funds_available_for_distribution*.1*.75
funds_available_for_succ_allocation_equity <- funds_available_for_distribution*.1*.25

# credit_ftes_rate <- 3988.58617857212
# non_credit_ftes_rate <- 3456.44149614
cdcp_rate <- 5313*(1+cola_2017_18/100)*(1+cola_2018_19/100)
# special_admits_rate <- 5634.5605750409
non_credit_ftes_rate <- 3259*(1+cola_2017_18/100)*(1+cola_2018_19/100)
special_admits_rate <- 5313*(1+cola_2017_18/100)*(1+cola_2018_19/100)


#SUPPLEMENTAL ALLOCATION DOLLAR AMOUNTS
# pell_grant_rate <- 929.568797133394000000
# ab540_rate <- 929.568797133394000000
# promise_grant_rate <- 929.568797133394000000

#SUCCESS ALLOCATION POINTS AND DOLLAR AMOUNTS
# ALL_rate <- 572.93879240842 
# EQUITY_rate <-144.385951096799

success_points <- tibble(
  achievement_type = c("associate_degrees_for_transfers",
                       "associate_degrees_for_transfers",
                       "associate_degrees_for_transfers",
                       "associate_degrees",
                       "associate_degrees",
                       "associate_degrees",
                       "baccalaureate_degrees",
                       "baccalaureate_degrees",
                       "baccalaureate_degrees",
                       "credit_certificates",
                       "credit_certificates",
                       "credit_certificates",
                       "transfer_level_math_and_english",
                       "transfer_level_math_and_english",
                       "transfer_level_math_and_english",
                       "nine_or_more_cte_units",
                       "nine_or_more_cte_units",
                       "nine_or_more_cte_units",
                       "transfers",
                       "transfers",
                       "transfers",
                       "regional_living_wage",
                       "regional_living_wage",
                       "regional_living_wage"),
  student_type = c("All Students",
                   "Pell Grant Students",
                   "Promise Grant Students",
                   "All Students",
                   "Pell Grant Students",
                   "Promise Grant Students",
                   "All Students",
                   "Pell Grant Students",
                   "Promise Grant Students",
                   "All Students",
                   "Pell Grant Students",
                   "Promise Grant Students",
                   "All Students",
                   "Pell Grant Students",
                   "Promise Grant Students",
                   "All Students",
                   "Pell Grant Students",
                   "Promise Grant Students",
                   "All Students",
                   "Pell Grant Students",
                   "Promise Grant Students",
                   "All Students",
                   "Pell Grant Students",
                   "Promise Grant Students"),
  points = c(4,6,4,
             3,4.5,3,
             3,4.5,3,
             2,3,2,
             2,3,2,
             1,1.5,1,
             1.5,2.25,1.5,
             1,1.5,1)
)

# student_success_rates <- tibble(
#   student_type = c("All Students", "Pell Grant Students","Promise Grant Students"),
#   rate = c(ALL_rate, EQUITY_rate, EQUITY_rate)
#   )

# success_rates <- success_points %>% left_join(student_success_rates)

```

```{r message=FALSE, warning=FALSE}

#cleaning base allocation data
base_allocation_data <- read_excel("C:/Users/10294029/Documents/GitHub/CC-League/Shiny App/Data/Base Allocation Data.xlsx") %>% 
  clean_names() %>% 
  mutate(inmates_ftes_credit = replace_na(inmates_ftes_credit, 0),
         ftes_excluding_inmates_special_admits = ftes_credit - (inmates_ftes_credit + special_admits_ftes_credit)) %>% 
  group_by(year)
basic_allocation <- read_excel("C:/Users/10294029/Documents/GitHub/CC-League/Shiny App/Data/Basic Allocations.xlsx") %>% 
  clean_names()

basic_allocation_cost <- basic_allocation %>%
  summarise(basic_allocation_total = sum(basic_allocation)) %>% 
  pull(basic_allocation_total)
  

#Splitting basic_allocation by year
base_allocation_tables <- group_split(base_allocation_data)

#list of Districts
districts <- bind_rows(base_allocation_tables) %>%   
  distinct(district) %>% 
  pull(district)

#list of years 
years <-  bind_rows(base_allocation_tables) %>%   
  distinct(year) %>% 
  pull(year)

# Calculating base allocation 
for(i in 1:length(base_allocation_tables)){
  if(i==1){
    base_allocation <- base_allocation_tables[[i]]
    
  } else {
    base_allocation <- left_join(base_allocation, base_allocation_tables[[i]],
                                  by = "district")
  }
}

# base_allocation_projection <- base_allocation %>%
#   mutate(year_proj = "2019-20",
#          ftes_credit_proj = ftes_credit*(1+ftes_growth_rate/100),
#          ftes_non_credit_proj = ftes_non_credit*(1+ftes_growth_rate/100),
#          cdcp_proj = cdcp*(1+ftes_growth_rate/100),
#          inmates_ftes_credit_proj = inmates_ftes_credit*(1+ftes_growth_rate/100),
#          special_admits_ftes_credit_proj = special_admits_ftes_credit*(1+ftes_growth_rate/100),
#          ftes_excluding_inmates_special_admits_proj = ftes_credit_proj - special_admits_ftes_credit_proj - inmates_ftes_credit_proj
#          ) %>%
#   select(district, contains("proj")) %>%
#   rename_all(., .funs = funs(str_replace(., "_proj", "")))

special_admits_inmates_cost <- base_allocation %>%
  mutate(special_admits_inmates_ftes = inmates_ftes_credit + special_admits_ftes_credit) %>%
  summarise(special_admits_inmates_total = sum(special_admits_inmates_ftes)*special_admits_rate
            ) %>%
  pull(special_admits_inmates_total)
# 
# 
# credit_ftes_allocation <- funds_available_for_base_allocation - basic_allocation_cost - special_admits_inmates_cost

```


```{r message=FALSE, warning=FALSE}
supplemental_alloc_data <- read_excel("C:/Users/10294029/Documents/GitHub/CC-League/Shiny App/Data/Supplemental Allocation Data.xlsx") %>% 
  clean_names()

supplemental_alloc_year <- supplemental_alloc_data %>% 
  distinct(year) %>% 
  mutate(n = seq(1:length(year)))

supplemental_alloc_data_split <- group_split(supplemental_alloc_data, year)


# Calculating supplemental allocation 
for(i in 1:length(supplemental_alloc_data_split)){
  if(i==1){
    supplemental_alloc_wide <- supplemental_alloc_data_split[[i]]
    names(supplemental_alloc_wide) <- paste0(names(supplemental_alloc_wide), "_", str_replace(supplemental_alloc_year[i,1], "-","_"))
    supplemental_alloc_wide <- rename_at(supplemental_alloc_wide,
                                          .vars = vars(1),
                                          .funs = funs(str_sub(.,1,str_length('district'))))
    } else {
      supplemental_alloc_data_temp <- supplemental_alloc_data_split[[i]]
      names(supplemental_alloc_data_temp) <- paste0(names(supplemental_alloc_data_temp), "_", str_replace(supplemental_alloc_year[i,1], "-","_"))
      supplemental_alloc_data_temp <- rename_at(supplemental_alloc_data_temp,
                                                .vars = vars(1),
                                                .funs = funs(str_sub(.,1,str_length('district'))))
      supplemental_alloc_wide <- left_join(supplemental_alloc_wide, supplemental_alloc_data_temp,
                                  by = "district")
  }
}


# supplemental_alloc_point_count <- supplemental_alloc_wide %>% 
#   mutate(year_proj = "2019-20",
#          pell_grant_recipients_totals_proj = pell_grant_recipients_totals_2017_18 + (pell_grant_recipients_totals_2017_18-pell_grant_recipients_totals_2016_17),
#          ab540_headcount_proj = ab540_headcount_2017_18 + (ab540_headcount_2017_18-ab540_headcount_2016_17),
#          california_promise_grant_recipients_totals_proj = california_promise_grant_recipients_totals_2017_18 + (california_promise_grant_recipients_totals_2017_18-california_promise_grant_recipients_totals_2016_17)) %>% 
#   select(district, contains("proj")) %>% 
#   mutate(supplemental_point_count = pell_grant_recipients_totals_proj+ab540_headcount_proj+california_promise_grant_recipients_totals_proj) %>% 
#   summarise(supplemental_point_count = sum(supplemental_point_count)) %>% 
#   pull(supplemental_point_count)
# 
# supplemental_alloc_rate = funds_available_for_supp_allocation / supplemental_alloc_point_count
# 
# supplemental_alloc_proj <- supplemental_alloc_wide %>% 
#   mutate(year_proj = "2019-20",
#          pell_grant_recipients_totals_proj = pell_grant_recipients_totals_2017_18 + (pell_grant_recipients_totals_2017_18-pell_grant_recipients_totals_2016_17),
#          ab540_headcount_proj = ab540_headcount_2017_18 + (ab540_headcount_2017_18-ab540_headcount_2016_17),
#          california_promise_grant_recipients_totals_proj = california_promise_grant_recipients_totals_2017_18 + (california_promise_grant_recipients_totals_2017_18-california_promise_grant_recipients_totals_2016_17)) %>%
#   mutate(supplemental_allocation = 
#               pell_grant_recipients_totals_proj*supplemental_alloc_rate + 
#               ab540_headcount_proj*supplemental_alloc_rate +
#               california_promise_grant_recipients_totals_proj*supplemental_alloc_rate
#          ) %>% 
#   select(District = district, supplemental_allocation)

```

```{r}
success_alloc_data <- read_excel("C:/Users/10294029/Documents/GitHub/CC-League/Shiny App/Data/Success Allocation Data.xlsx") %>% 
  clean_names()

success_alloc_data_year <- success_alloc_data %>% 
  distinct(year, student_type) %>% 
  mutate(student_type = case_when(str_detect(student_type, "All")~ "_ALL",
                                  str_detect(student_type, "Pell")~ "_PELL",
                                  TRUE ~ "_PROMISE"),
         year = paste0(year, student_type)) %>% 
  distinct(year) %>% 
  mutate(n = row_number())

success_alloc_data_split <- group_split(success_alloc_data, year, student_type)

# Calculating supplemental allocation 
for(i in 1:length(success_alloc_data_split)){
  if(i==1){
    success_alloc_wide <- success_alloc_data_split[[i]]
    names(success_alloc_wide) <- paste0(names(success_alloc_wide), "_", str_replace(success_alloc_data_year[i,1], "-","_"))
    success_alloc_wide <- rename_at(success_alloc_wide,
                                          .vars = vars(1),
                                          .funs = funs(str_sub(.,1,str_length('district'))))
    } else {
      success_alloc_temp <- success_alloc_data_split[[i]]
      names(success_alloc_temp) <- paste0(names(success_alloc_temp), "_", str_replace(success_alloc_data_year[i,1], "-","_"))
      success_alloc_temp <- rename_at(success_alloc_temp,
                                                .vars = vars(1),
                                                .funs = funs(str_sub(.,1,str_length('district'))))
      success_alloc_wide <- left_join(success_alloc_wide, success_alloc_temp,
                                  by = "district")
  }
}

success_alloc_proj <- success_alloc_wide %>% 
  mutate(year_proj_ALL = "2019-20",
         year_proj_PELL = "2019-20",
         year_proj_PROMISE = "2019-20",
         
         associate_degrees_for_transfers_proj_ALL = associate_degrees_for_transfers_2017_18_ALL + (associate_degrees_for_transfers_2017_18_ALL - associate_degrees_for_transfers_2016_17_ALL),
         associate_degrees_for_transfers_proj_PELL = associate_degrees_for_transfers_2017_18_PELL + (associate_degrees_for_transfers_2017_18_PELL - associate_degrees_for_transfers_2016_17_PELL),
         associate_degrees_for_transfers_proj_PROMISE = associate_degrees_for_transfers_2017_18_PROMISE + (associate_degrees_for_transfers_2017_18_PROMISE - associate_degrees_for_transfers_2016_17_PROMISE),

         associate_degrees_proj_ALL = associate_degrees_2017_18_ALL + (associate_degrees_2017_18_ALL - associate_degrees_2016_17_ALL),
         associate_degrees_proj_PELL = associate_degrees_2017_18_PELL + (associate_degrees_2017_18_PELL - associate_degrees_2016_17_PELL),
         associate_degrees_proj_PROMISE = associate_degrees_2017_18_PROMISE + (associate_degrees_2017_18_PROMISE - associate_degrees_2016_17_PROMISE),
         
         baccalaureate_degrees_proj_ALL = baccalaureate_degrees_2017_18_ALL + (baccalaureate_degrees_2017_18_ALL - baccalaureate_degrees_2016_17_ALL),
         baccalaureate_degrees_proj_PELL = baccalaureate_degrees_2017_18_PELL + (baccalaureate_degrees_2017_18_PELL - baccalaureate_degrees_2016_17_PELL),
         baccalaureate_degrees_proj_PROMISE = baccalaureate_degrees_2017_18_PELL + (baccalaureate_degrees_2017_18_PELL- baccalaureate_degrees_2016_17_PELL),
         
         credit_certificates_proj_ALL = credit_certificates_2017_18_ALL + (credit_certificates_2017_18_ALL - credit_certificates_2016_17_ALL),
         credit_certificates_proj_PELL = credit_certificates_2017_18_PELL + (credit_certificates_2017_18_PELL - credit_certificates_2016_17_PELL),
         credit_certificates_proj_PROMISE = credit_certificates_2017_18_PROMISE + (credit_certificates_2017_18_PROMISE - credit_certificates_2016_17_PROMISE),
         
         transfer_level_math_and_english_proj_ALL = transfer_level_math_and_english_2017_18_ALL + (transfer_level_math_and_english_2017_18_ALL - transfer_level_math_and_english_2016_17_ALL),
         transfer_level_math_and_english_proj_PELL = transfer_level_math_and_english_2017_18_PELL + (transfer_level_math_and_english_2017_18_PELL - transfer_level_math_and_english_2016_17_PELL),
         transfer_level_math_and_english_proj_PROMISE = transfer_level_math_and_english_2017_18_PROMISE + (transfer_level_math_and_english_2017_18_PROMISE - transfer_level_math_and_english_2016_17_PROMISE),
         
         nine_or_more_cte_units_proj_ALL = nine_or_more_cte_units_2017_18_ALL + (nine_or_more_cte_units_2017_18_ALL - nine_or_more_cte_units_2016_17_ALL),
         nine_or_more_cte_units_proj_PELL = nine_or_more_cte_units_2017_18_PELL + (nine_or_more_cte_units_2017_18_PELL - nine_or_more_cte_units_2016_17_PELL),
         nine_or_more_cte_units_proj_PROMISE = nine_or_more_cte_units_2017_18_PROMISE + (nine_or_more_cte_units_2017_18_PROMISE - nine_or_more_cte_units_2016_17_PROMISE),
         
         transfers_proj_ALL = transfers_2017_18_ALL + (transfers_2017_18_ALL - transfers_2016_17_ALL),
         transfers_proj_PELL = transfers_2017_18_PELL + (transfers_2017_18_PELL - transfers_2016_17_PELL),
         transfers_proj_PROMISE = transfers_2017_18_PROMISE + (transfers_2017_18_PROMISE - transfers_2016_17_PROMISE),
         
         regional_living_wage_proj_ALL = regional_living_wage_2017_18_ALL + (regional_living_wage_2017_18_ALL - regional_living_wage_2016_17_ALL),
         regional_living_wage_proj_PELL = regional_living_wage_2017_18_PELL + (regional_living_wage_2017_18_PELL - regional_living_wage_2016_17_PELL),
         regional_living_wage_proj_PROMISE = regional_living_wage_2017_18_PROMISE + (regional_living_wage_2017_18_PROMISE - regional_living_wage_2016_17_PROMISE)
        ) %>% 
  select(district, contains("_proj_")) %>% 
  rename_at(.,
            .vars = vars(contains("_proj_")),
            .funs = funs(str_replace(., "_proj", "")))

success_alloc_all_proj <- success_alloc_proj %>% 
  select(district, contains("_ALL")) %>% 
  rename_at(.,
            .vars = vars(contains("_ALL")),
            .funs = funs(str_replace(., "_ALL", ""))) %>% 
  mutate(student_type = "All Students")

success_alloc_pell_proj <- success_alloc_proj %>% 
  select(district, contains("_PELL")) %>% 
  rename_at(.,
            .vars = vars(contains("_PELL")),
            .funs = funs(str_replace(., "_PELL", ""))) %>% 
  mutate(student_type = "Pell Grant Students")

success_alloc_promise_proj <- success_alloc_proj %>% 
  select(district, contains("_PROMISE")) %>% 
  rename_at(.,
            .vars = vars(contains("_PROMISE")),
            .funs = funs(str_replace(., "_PROMISE", ""))) %>% 
  mutate(student_type = "Promise Grant Students")

success_alloc_proj_stacked <- bind_rows(success_alloc_all_proj, success_alloc_pell_proj, success_alloc_promise_proj)


#THIS STEP WILL NEED TO BE EVALUATED. RIGHT NOW WE ARE USING 3 NON-CONTINUOUS YEARS TO CALCULATE THE THREE-YEAR AVERAGE, WHICH SEEMS INAPPROPRIATE
# success_main_point_count <- success_alloc_proj_stacked %>%
#   arrange(district, student_type) %>% 
#   select(-year) %>% 
#   gather(key = "achievement_type", value = "n_ftes", -district,-student_type) %>% 
#   filter(student_type == "All Students") %>% 
#   group_by(achievement_type, student_type) %>% 
#   summarise(main_success_ftes = sum(n_ftes)) %>% 
#   left_join(success_points) %>% 
#   mutate(main_success_points = main_success_ftes*points) %>% 
#   ungroup %>% 
#   summarise(main_success_points = sum(main_success_points)) %>% 
#   pull(main_success_points)
# 
# success_main_rate = funds_available_for_succ_allocation_main / success_main_point_count
# 
# success_equity_point_count <- success_alloc_proj_stacked %>%
#   arrange(district, student_type) %>% 
#   select(-year) %>% 
#   gather(key = "achievement_type", value = "n_ftes", -district,-student_type) %>% 
#   filter(student_type != "All Students") %>% 
#   group_by(achievement_type, student_type) %>% 
#   summarise(equity_success_points = sum(n_ftes)) %>% 
#   left_join(success_points) %>% 
#   mutate(equity_success_points = equity_success_points*points) %>% 
#   ungroup %>% 
#   summarise(equity_success_points = sum(equity_success_points)) %>% 
#   pull(equity_success_points)
# 
# success_equity_rate = funds_available_for_succ_allocation_equity / success_equity_point_count
# 
# student_success_rates <- tibble(
#   student_type = c("All Students", "Pell Grant Students","Promise Grant Students"),
#   rate = c(success_main_rate, success_equity_rate, success_equity_rate)
#   )
# 
# success_rates <- success_points %>% left_join(student_success_rates)
# 
# success_alloc_to_join <- success_alloc_proj_stacked %>%
#   arrange(district, student_type) %>% 
#   select(-year) %>% 
#   gather(key = "achievement_type", value = "n_ftes", -district,-student_type) %>% 
#   left_join(success_rates) %>% 
#   mutate(success_alloc = n_ftes*points*rate) %>%
#   group_by(district) %>% 
#   summarise(success_allocation = sum(success_alloc)) %>% 
#   rename(District = district)

```


```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=TRUE}
apportionment_2017_18 <- read_excel("C:/Users/10294029/Documents/GitHub/CC-League/Shiny App/Data/2017-18 Apportionments.xlsx") %>% 
  clean_names() %>% 
  select(District = district, apportionment_2017_18)

# apportionment_2017_18
```


```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}

basic_aid_districts <- c("Marin", "MiraCosta", "San Jose", "San Mateo", "South Orange County", "West Valley-Mission2")

```


```{r message=FALSE, warning=FALSE, include=FALSE}
library(shiny)
library(shinyWidgets)
library(DT)
library(plotly)


#Making Shiny UI
ui <- fluidPage(
  titlePanel("Student Centered Funding Formula"),
  sidebarLayout(
    sidebarPanel(
      width = 3,
      pickerInput("district", "District:",
                  choices = districts,
                  selected = districts,
                  multiple = T,
                  options=list(`actions-Box`= TRUE,
                               `selected-text-format` = "count > 1")),
      uiOutput("dynamic_inputs"),
      checkboxInput("new_money_old_money",label = "New Money Only?",value = F),
      # pickerInput("new_money_old_money", "New Money or Total Money Available:",
      #             choices = c("New Money Only", "Total Money Available"),
      #             selected = "Total Money Available",
      #             multiple = F),
      selectInput("starting_avg_year", "Starting Average Year:",
                  choices = c("2018-19" = "2018-19",
                     "3-Year Average"  = "2016-17"),
                  selected = "2016-17"),
      # numericInput("funds_available_for_distribution", "Funds Available for Distribution :",
      #             min = 0, max = 8000000000, value = funds_available_for_distribution),
      sliderInput("ftes_growth_rate", "Growth Rate:",
                   min = 0, max = 1.5, value = ftes_growth_rate, post = "%", step = 0.01)
                ),
    
    
      mainPanel(
        
        tabsetPanel(
          type = "tabs",
          tabPanel("Apportionment Calculator", DT::dataTableOutput("base_table"), class = 'rightAlign')
          ,tabPanel("Distribution by District", 
                    plotlyOutput("apportionment_hist", height = "300px"), 
                    plotlyOutput("apportionment_bar", height = "620px")
                    )
          ,tabPanel("Apportionment per FTES"
                    ,plotlyOutput("per_ftes_box_plots", height="460px")
                    ,plotlyOutput("per_ftes_bar", height="460px")
                    )
          ,tabPanel("District Apportionments YoY"
                    ,plotlyOutput("yoy_change_bar", height = "920px"))
          
        )
      )
  )
# , hr()
# ,print('[1] Indicates a Basic Aid District. For these six districts, "Hold Harmless" amounts are not calculated and their 2019-20 SCFF Apportionment is equal to their 2019-20 Minimun SCFF Apportionment.')

)

total_money_color <-"#5DA5DA"
# total_money_color_light <- "#e8f5ff"
new_money_color <-'#FAA43A'
# new_money_color_light <- "#ffeed9"

winners_color <- '#60BD68'
losers_color <- "#B276B2 "

#Back-end server function
server <- function(input, output, session) {
  
  # Updating default funds available for distribution based on new money selection

  output$dynamic_inputs <- renderUI({
    # if(input$new_money_old_money == F){ ## Total Monies
      tagList(
      sliderInput("total_funds_available_for_distribution", "Total Money Available for Distribution :",
                  min = 0, max = 8000000000, value = funds_available_for_distribution, pre = "$", step = 1600000000),
      sliderInput("New_funds_available_for_distribution", "New Money Available for Distribution :",
                  min = 0, max = 1000000000, value = 405000000, pre = "$", step = 5000000)
      )
    # }else{## NEW Monies
    #   tagList(
    #   sliderInput("funds_available_for_distribution", "Funds Available for Distribution :",
    #               min = 0, max = 8000000000, value = 405000000, pre = "$", step = 1600000000)
    #   )
    # }
  })
  
  total_money_color_dynamic <- reactive({
     if(input$new_money_old_money == F){##Total Money
       "#5DA5DA"
     }else{
       "#b8e0ff"
     }
  })
  
  new_money_color_dynamic <- reactive({
    if(input$new_money_old_money == F){##Total Money
       "#ffdeb5"
     }else{
       "#FAA43A"
     }
  })
  
  TotalMoney.dataInput <- reactive({
              ##  Calculating the 70/20/10 breakdown
                funds_available_for_base_allocation <- input$total_funds_available_for_distribution*.7
                funds_available_for_supp_allocation <- input$total_funds_available_for_distribution*.2
                funds_available_for_succ_allocation_main <- input$total_funds_available_for_distribution*.1*.75
                funds_available_for_succ_allocation_equity <- input$total_funds_available_for_distribution*.1*.25 
                
              ## Calculating base alloction rates
                base_allocation_projection <- base_allocation %>% 
                  mutate(year_proj = "2019-20",
                         ftes_credit_proj = ftes_credit*(1+input$ftes_growth_rate/100),
                         ftes_non_credit_proj = ftes_non_credit*(1+input$ftes_growth_rate/100),
                         cdcp_proj = cdcp*(1+input$ftes_growth_rate/100),
                         inmates_ftes_credit_proj = inmates_ftes_credit*(1+input$ftes_growth_rate/100),
                         special_admits_ftes_credit_proj = special_admits_ftes_credit*(1+input$ftes_growth_rate/100),
                         ftes_excluding_inmates_special_admits_proj = ftes_credit_proj - special_admits_ftes_credit_proj - inmates_ftes_credit_proj
                         ) %>% 
                  select(district, contains("proj")) %>% 
                  rename_all(., .funs = funs(str_replace(., "_proj", "")))
              
                credit_ftes_allocation <- funds_available_for_base_allocation - basic_allocation_cost - special_admits_inmates_cost
                
                if(input$starting_avg_year =="2018-19"){
                  base_allocation_projection_stacked <- bind_rows(base_allocation_tables, base_allocation_projection) %>% 
                    mutate(cal_year = as.numeric(str_sub(year, 1, 4))) %>% 
                    filter(cal_year >=2018)
                }else{
                  base_allocation_projection_stacked <- bind_rows(base_allocation_tables, base_allocation_projection) %>% 
                    mutate(cal_year = as.numeric(str_sub(year, 1, 4))) %>% 
                    filter(cal_year >2016)
                }
                
                avg_ftes_credit <- base_allocation_projection_stacked %>% 
                  group_by(district) %>%
                  arrange(district) %>% 
                  mutate(avg_ftes_credit = mean(ftes_excluding_inmates_special_admits)) %>% 
                  ungroup %>% 
                  distinct(district, avg_ftes_credit) %>% 
                  summarize(total_avg_ftes_credit = sum(avg_ftes_credit)) %>% 
                  pull(total_avg_ftes_credit)
                
                credit_ftes_rate <- credit_ftes_allocation / avg_ftes_credit
                
              ## Calculating Supplemental alloction rates
                supplemental_alloc_point_count <- supplemental_alloc_wide %>% 
                mutate(year_proj = "2019-20",
                       pell_grant_recipients_totals_proj = pell_grant_recipients_totals_2017_18 +
                         (pell_grant_recipients_totals_2017_18-pell_grant_recipients_totals_2016_17),
                       ab540_headcount_proj = ab540_headcount_2017_18 + (ab540_headcount_2017_18-ab540_headcount_2016_17),
                       california_promise_grant_recipients_totals_proj = california_promise_grant_recipients_totals_2017_18 +
                         (california_promise_grant_recipients_totals_2017_18-california_promise_grant_recipients_totals_2016_17)) %>% 
                select(district, contains("proj")) %>% 
                mutate(supplemental_point_count = pell_grant_recipients_totals_proj+ab540_headcount_proj+california_promise_grant_recipients_totals_proj) %>% 
                summarise(supplemental_point_count = sum(supplemental_point_count)) %>% 
                pull(supplemental_point_count)
              
              supplemental_alloc_rate = funds_available_for_supp_allocation / supplemental_alloc_point_count
              
              supplemental_alloc_proj <- supplemental_alloc_wide %>% 
                mutate(year_proj = "2019-20",
                       pell_grant_recipients_totals_proj = pell_grant_recipients_totals_2017_18 +
                         (pell_grant_recipients_totals_2017_18-pell_grant_recipients_totals_2016_17),
                       ab540_headcount_proj = ab540_headcount_2017_18 + (ab540_headcount_2017_18-ab540_headcount_2016_17),
                       california_promise_grant_recipients_totals_proj = california_promise_grant_recipients_totals_2017_18 +
                         (california_promise_grant_recipients_totals_2017_18-california_promise_grant_recipients_totals_2016_17)) %>%
                mutate(supplemental_allocation = 
                            pell_grant_recipients_totals_proj*supplemental_alloc_rate + 
                            ab540_headcount_proj*supplemental_alloc_rate +
                            california_promise_grant_recipients_totals_proj*supplemental_alloc_rate
                       ) %>% 
                select(District = district, supplemental_allocation)
              
              ## Calculating Success alloction rates
              success_main_point_count <- success_alloc_proj_stacked %>%
                  arrange(district, student_type) %>% 
                  select(-year) %>% 
                  gather(key = "achievement_type", value = "n_ftes", -district,-student_type) %>% 
                  filter(student_type == "All Students") %>% 
                  group_by(achievement_type, student_type) %>% 
                  summarise(main_success_ftes = sum(n_ftes)) %>% 
                  left_join(success_points) %>% 
                  mutate(main_success_points = main_success_ftes*points) %>% 
                  ungroup %>% 
                  summarise(main_success_points = sum(main_success_points)) %>% 
                  pull(main_success_points)
                
                success_main_rate = funds_available_for_succ_allocation_main / success_main_point_count
                
                success_equity_point_count <- success_alloc_proj_stacked %>%
                  arrange(district, student_type) %>% 
                  select(-year) %>% 
                  gather(key = "achievement_type", value = "n_ftes", -district,-student_type) %>% 
                  filter(student_type != "All Students") %>% 
                  group_by(achievement_type, student_type) %>% 
                  summarise(equity_success_points = sum(n_ftes)) %>% 
                  left_join(success_points) %>% 
                  mutate(equity_success_points = equity_success_points*points) %>% 
                  ungroup %>% 
                  summarise(equity_success_points = sum(equity_success_points)) %>% 
                  pull(equity_success_points)
                
                success_equity_rate = funds_available_for_succ_allocation_equity / success_equity_point_count
                
                student_success_rates <- tibble(
                  student_type = c("All Students", "Pell Grant Students","Promise Grant Students"),
                  rate = c(success_main_rate, success_equity_rate, success_equity_rate)
                  )
                
                success_rates <- success_points %>% left_join(student_success_rates)
                
                success_alloc_to_join <- success_alloc_proj_stacked %>%
                  arrange(district, student_type) %>% 
                  select(-year) %>% 
                  gather(key = "achievement_type", value = "n_ftes", -district,-student_type) %>% 
                  left_join(success_rates) %>% 
                  mutate(success_alloc = n_ftes*points*rate) %>%
                  group_by(district) %>% 
                  summarise(success_allocation = sum(success_alloc)) %>% 
                  rename(District = district)
                                                          
               ## Making the table  
               final_allocation <- base_allocation_projection_stacked %>% 
                  filter(district %in% input$district) %>%
                  group_by(district) %>%
                  arrange(district) %>% 
                  mutate(avg_ftes_credit = mean(ftes_excluding_inmates_special_admits)) %>% 
                  ungroup %>% 
                  filter(year == "2019-20") %>% 
                  select(district, year, cal_year, avg_ftes_credit) %>% 
                    #This joins on the previous years special admits, inmates, non credit ftes, and cdcp figures, which is what the formula calls for
                  left_join(base_allocation_projection_stacked %>% 
                              filter(year == "2018-19") %>% 
                              select(district, special_admits_ftes_credit, inmates_ftes_credit, ftes_credit,cdcp,ftes_non_credit)) %>% 
                  mutate(special_admits_ftes_credit = special_admits_ftes_credit+inmates_ftes_credit) %>% 
                  select(district, year, ftes_non_credit, cdcp, ftes_credit, avg_ftes_credit, special_admits_ftes_credit) %>% 
                  mutate() %>% 
                  left_join(basic_allocation) %>% 
                  mutate(base_allocation = ftes_non_credit*non_credit_ftes_rate + 
                                                    cdcp*cdcp_rate + 
                                                    avg_ftes_credit*credit_ftes_rate + 
                                                    special_admits_ftes_credit*special_admits_rate + 
                                                    basic_allocation) %>% 
                  select(District = district, base_allocation,ftes_non_credit,cdcp,ftes_credit,special_admits_ftes_credit) %>% 
                  left_join(supplemental_alloc_proj) %>% 
                  left_join(success_alloc_to_join) %>%
                  left_join(apportionment_2017_18)
               
               final_allocation
               })
  NewMoney.dataInput <- reactive({
    ##  Calculating the 70/20/10 breakdown
                funds_available_for_base_allocation <- input$New_funds_available_for_distribution*.7
                funds_available_for_supp_allocation <- input$New_funds_available_for_distribution*.2
                funds_available_for_succ_allocation_main <- input$New_funds_available_for_distribution*.1*.75
                funds_available_for_succ_allocation_equity <- input$New_funds_available_for_distribution*.1*.25  
                
                
              ## Calculating base alloction rates
                base_allocation_projection <- base_allocation %>% 
                  mutate(year_proj = "2019-20",
                         ftes_credit_proj = ftes_credit*(1+input$ftes_growth_rate/100),
                         ftes_non_credit_proj = ftes_non_credit*(1+input$ftes_growth_rate/100),
                         cdcp_proj = cdcp*(1+input$ftes_growth_rate/100),
                         inmates_ftes_credit_proj = inmates_ftes_credit*(1+input$ftes_growth_rate/100),
                         special_admits_ftes_credit_proj = special_admits_ftes_credit*(1+input$ftes_growth_rate/100),
                         ftes_excluding_inmates_special_admits_proj = ftes_credit_proj - special_admits_ftes_credit_proj - inmates_ftes_credit_proj
                         ) %>% 
                  select(district, contains("proj")) %>% 
                  rename_all(., .funs = funs(str_replace(., "_proj", "")))
              
                credit_ftes_allocation <- funds_available_for_base_allocation#- basic_allocation_cost - special_admits_inmates_cost
                
                if(input$starting_avg_year =="2018-19"){
                  base_allocation_projection_stacked <- bind_rows(base_allocation_tables, base_allocation_projection) %>% 
                    mutate(cal_year = as.numeric(str_sub(year, 1, 4))) %>% 
                    filter(cal_year >=2018)
                }else{
                  base_allocation_projection_stacked <- bind_rows(base_allocation_tables, base_allocation_projection) %>% 
                    mutate(cal_year = as.numeric(str_sub(year, 1, 4))) %>% 
                    filter(cal_year >2016)
                }
                
                avg_ftes_credit <- base_allocation_projection_stacked %>% 
                    group_by(district) %>%
                    arrange(district) %>% 
                    mutate(avg_ftes_credit = mean(ftes_excluding_inmates_special_admits)) %>% 
                    ungroup %>% 
                    distinct(district, avg_ftes_credit) %>% 
                    summarize(total_avg_ftes_credit = sum(avg_ftes_credit)) %>% 
                    pull(total_avg_ftes_credit)
                
                ftes_credits_equal_weight_cost <- base_allocation %>%
                  mutate(ftes_credits_equal_weight = ftes_non_credit+cdcp+inmates_ftes_credit + special_admits_ftes_credit) %>%
                  summarise(ftes_credits_equal_weight = sum(ftes_credits_equal_weight)#*special_admits_rate
                            ) %>%
                  pull(ftes_credits_equal_weight)
                
                base_allocation_rate <- credit_ftes_allocation / (avg_ftes_credit+ftes_credits_equal_weight_cost)

                     
              ## Calculating Supplemental alloction rates
                supplemental_alloc_point_count <- supplemental_alloc_wide %>% 
                mutate(year_proj = "2019-20",
                       pell_grant_recipients_totals_proj = pell_grant_recipients_totals_2017_18 +
                         (pell_grant_recipients_totals_2017_18-pell_grant_recipients_totals_2016_17),
                       ab540_headcount_proj = ab540_headcount_2017_18 + (ab540_headcount_2017_18-ab540_headcount_2016_17),
                       california_promise_grant_recipients_totals_proj = california_promise_grant_recipients_totals_2017_18 +
                         (california_promise_grant_recipients_totals_2017_18-california_promise_grant_recipients_totals_2016_17)) %>% 
                select(district, contains("proj")) %>% 
                mutate(supplemental_point_count = pell_grant_recipients_totals_proj+ab540_headcount_proj+california_promise_grant_recipients_totals_proj) %>% 
                summarise(supplemental_point_count = sum(supplemental_point_count)) %>% 
                pull(supplemental_point_count)
              
              supplemental_alloc_rate = funds_available_for_supp_allocation / supplemental_alloc_point_count
              
              supplemental_alloc_proj <- supplemental_alloc_wide %>% 
                mutate(year_proj = "2019-20",
                       pell_grant_recipients_totals_proj = pell_grant_recipients_totals_2017_18 +
                         (pell_grant_recipients_totals_2017_18-pell_grant_recipients_totals_2016_17),
                       ab540_headcount_proj = ab540_headcount_2017_18 + (ab540_headcount_2017_18-ab540_headcount_2016_17),
                       california_promise_grant_recipients_totals_proj = california_promise_grant_recipients_totals_2017_18 +
                         (california_promise_grant_recipients_totals_2017_18-california_promise_grant_recipients_totals_2016_17)) %>%
                mutate(supplemental_allocation = 
                            pell_grant_recipients_totals_proj*supplemental_alloc_rate + 
                            ab540_headcount_proj*supplemental_alloc_rate +
                            california_promise_grant_recipients_totals_proj*supplemental_alloc_rate
                       ) %>% 
                select(District = district, supplemental_allocation)
              
              
              
              ## Calculating Success alloction rates
              success_main_point_count <- success_alloc_proj_stacked %>%
                  arrange(district, student_type) %>% 
                  select(-year) %>% 
                  gather(key = "achievement_type", value = "n_ftes", -district,-student_type) %>% 
                  filter(student_type == "All Students") %>% 
                  group_by(achievement_type, student_type) %>% 
                  summarise(main_success_ftes = sum(n_ftes)) %>% 
                  left_join(success_points) %>% 
                  mutate(main_success_points = main_success_ftes*points) %>% 
                  ungroup %>% 
                  summarise(main_success_points = sum(main_success_points)) %>% 
                  pull(main_success_points)
                
                success_main_rate = funds_available_for_succ_allocation_main / success_main_point_count
                
                success_equity_point_count <- success_alloc_proj_stacked %>%
                  arrange(district, student_type) %>% 
                  select(-year) %>% 
                  gather(key = "achievement_type", value = "n_ftes", -district,-student_type) %>% 
                  filter(student_type != "All Students") %>% 
                  group_by(achievement_type, student_type) %>% 
                  summarise(equity_success_points = sum(n_ftes)) %>% 
                  left_join(success_points) %>% 
                  mutate(equity_success_points = equity_success_points*points) %>% 
                  ungroup %>% 
                  summarise(equity_success_points = sum(equity_success_points)) %>% 
                  pull(equity_success_points)
                
                success_equity_rate = funds_available_for_succ_allocation_equity / success_equity_point_count
                
                student_success_rates <- tibble(
                  student_type = c("All Students", "Pell Grant Students","Promise Grant Students"),
                  rate = c(success_main_rate, success_equity_rate, success_equity_rate)
                  )
                
                success_rates <- success_points %>% left_join(student_success_rates)
                
                success_alloc_to_join <- success_alloc_proj_stacked %>%
                  arrange(district, student_type) %>% 
                  select(-year) %>% 
                  gather(key = "achievement_type", value = "n_ftes", -district,-student_type) %>% 
                  left_join(success_rates) %>% 
                  mutate(success_alloc = n_ftes*points*rate) %>%
                  group_by(district) %>% 
                  summarise(success_allocation = sum(success_alloc)) %>% 
                  rename(District = district)
                                                          
               ## Making the table  
               final_allocation <- base_allocation_projection_stacked %>% 
                  filter(district %in% input$district) %>%
                  group_by(district) %>%
                  arrange(district) %>% 
                  mutate(avg_ftes_credit = mean(ftes_excluding_inmates_special_admits)) %>% 
                  ungroup %>% 
                  filter(year == "2019-20") %>% 
                  select(district, year, cal_year, avg_ftes_credit) %>% 
                    #This joins on the previous years special admits, inmates, non credit ftes, and cdcp figures, which is what the formula calls for
                  left_join(base_allocation_projection_stacked %>% 
                              filter(year == "2018-19") %>% 
                              select(district, special_admits_ftes_credit, inmates_ftes_credit, ftes_credit,cdcp,ftes_non_credit)) %>% 
                  mutate(special_admits_ftes_credit = special_admits_ftes_credit+inmates_ftes_credit) %>% 
                  select(district, year, ftes_non_credit, cdcp,ftes_credit, avg_ftes_credit, special_admits_ftes_credit) %>% 
                  mutate() %>% 
                  # left_join(basic_allocation) %>% 
                  mutate(base_allocation = ftes_non_credit*base_allocation_rate 
                                                    +cdcp*base_allocation_rate  
                                                    +avg_ftes_credit*base_allocation_rate  
                                                    +special_admits_ftes_credit*base_allocation_rate  
                                                    # +basic_allocation
                         ) %>% 
                  select(District = district, base_allocation,ftes_non_credit,cdcp,ftes_credit,special_admits_ftes_credit) %>% 
                  left_join(supplemental_alloc_proj) %>% 
                  left_join(success_alloc_to_join) %>%
                  left_join(apportionment_2017_18) %>%
                  mutate(scff_apportionment_2019_20 = base_allocation + supplemental_allocation + success_allocation)
               
               final_allocation
  })
  
  
  
   # Generate table ----
  output$base_table <- DT::renderDataTable({
      if(input$new_money_old_money == F){## Total Monies
          plot_data <- TotalMoney.dataInput() 
          
          plot_data <- plot_data %>% 
              mutate(scff_apportionment_2019_20 = base_allocation + supplemental_allocation + success_allocation) %>%
              mutate(`Base Allocation` = format( base_allocation , big.mark = ","),
                     `Supplemental Allocation` = format(supplemental_allocation, big.mark = ","),
                     `Success Allocation` = format(success_allocation, big.mark = ",", digits = 0),
                     `2019-20 SCFF Minimum Apportionment` = format(scff_apportionment_2019_20, big.mark = ","),
                     `2017-18 Apportionment (Grown at COLA to 2019-20)` =
                       format(apportionment_2017_18*(1+(cola_2017_18)/100)*(1+(cola_2018_19)/100), big.mark = ","),
                     # `Basic Aid District` = if_else(District %in% basic_aid_districts, "Yes",""),
                     `Hold Harmless` = str_replace(format(case_when(District %in% basic_aid_districts ~ 0,
                                              apportionment_2017_18*(1+(cola_2017_18)/100)*(1+(cola_2018_19)/100) > scff_apportionment_2019_20 ~
                                              apportionment_2017_18*(1+(cola_2017_18)/100)*(1+(cola_2018_19)/100) - scff_apportionment_2019_20,TRUE ~ 0), 
                                                          big.mark = ",", digits = 0, scientific = F),
                                                   pattern = "\\b0\\b", "-"),
                     `2019-20 SCFF Aportionment` = str_replace(
                       format(case_when(District %in% basic_aid_districts ~ base_allocation + supplemental_allocation + success_allocation,
                                        apportionment_2017_18*(1+(cola_2017_18)/100)*(1+(cola_2018_19)/100) > base_allocation + supplemental_allocation + success_allocation~
                                          apportionment_2017_18*(1+(cola_2017_18)/100)*(1+(cola_2018_19)/100),
                                        TRUE ~ base_allocation + supplemental_allocation + success_allocation) 
                              ,big.mark = ",", digits = 0, scientific = F)
                       ,pattern = "\\b0\\b", "-"
                       )
                     )%>%
              select(-contains("_"),-cdcp)
           
              plot_data$`2019-20 SCFF Aportionment` <- paste0("<b>", plot_data$`2019-20 SCFF Aportionment`, "</b>")
           
              plot_data$District <- if_else(plot_data$District %in% basic_aid_districts,
                                                   paste0(plot_data$District,"<sup>[1]</sup>"),
                                                   plot_data$District)
                                              
              plot_data
      }else{## NEW Monies
         plot_data <- NewMoney.dataInput()
         
         plot_data <- plot_data %>% 
            mutate(`Base Allocation` = format(base_allocation , big.mark = ","),
                                       `Supplemental Allocation` = format(supplemental_allocation, big.mark = ","),
                                       `Success Allocation` = format(success_allocation, big.mark = ",", digits = 0),
                                       `2019-20 SCFF Additional Apportionment` = format(scff_apportionment_2019_20, big.mark = ","),
                                       `2017-18 Apportionment (Grown at COLA to 2019-20)` =
                                         format(apportionment_2017_18*(1+(cola_2017_18)/100)*(1+(cola_2018_19)/100), big.mark = ","),
                                       # `Basic Aid District` = if_else(District %in% basic_aid_districts, "Yes",""),
                                       `2019-20 SCFF Aportionment` = format(apportionment_2017_18*(1+(cola_2017_18)/100)*(1+(cola_2018_19)/100) + scff_apportionment_2019_20
                                                                            , big.mark = ","))%>%
            select(-contains("_"),-cdcp)

            plot_data$`2019-20 SCFF Aportionment` <- paste0("<b>", plot_data$`2019-20 SCFF Aportionment`, "</b>")

            plot_data$District <- if_else(plot_data$District %in% basic_aid_districts,
                                                 paste0(plot_data$District,"<sup>[1]</sup>"),
                                                 plot_data$District)

            plot_data
          }
                                              
        }
          , rownames = F
          , escape = FALSE
          , options = list(pageLength = 20, searching = FALSE, lengthChange=FALSE
                           ,columnDefs = list(list(width = '200px', targets = "_all"),
                                              list(class = "dt-right", targets =c(-1))
                                              )
                           )
)
  
                                          
  # DISTRIBUTION BY DISTRICT ----
   ## Generate scatter ----
  output$apportionment_hist <- renderPlotly({
      if(input$new_money_old_money == F){## Total Monies
          plot_data <- TotalMoney.dataInput() 
          
          plot_data <- plot_data %>% 
            mutate(scff_apportionment_2019_20 = base_allocation + supplemental_allocation + success_allocation) %>%
            mutate(apportionment_difference = scff_apportionment_2019_20 - (apportionment_2017_18*(1+(cola_2017_18)/100)*(1+(cola_2018_19)/100))) %>% 
            mutate(apportionment_2017_18_grown_at_cola = apportionment_2017_18*(1+(cola_2017_18)/100)*(1+(cola_2018_19)/100))
           
      }else{## NEW Monies
          plot_data <- NewMoney.dataInput()
         
          plot_data <- plot_data %>% 
            mutate(scff_apportionment_2019_20 = base_allocation + supplemental_allocation + success_allocation) %>%
            mutate(apportionment_difference = scff_apportionment_2019_20 #+ (apportionment_2017_18*(1+(cola_2017_18)/100)*(1+(cola_2018_19)/100)) 
                   ,apportionment_2017_18_grown_at_cola = apportionment_2017_18*(1+(cola_2017_18)/100)*(1+(cola_2018_19)/100))
      }     
    
    
        districts_improved <- plot_data %>% 
          filter(apportionment_difference>=0,
                 !District %in% basic_aid_districts)
        
        districts_basic_aid <- plot_data %>% 
          filter(District %in% basic_aid_districts)
        
        districts_harmed <- plot_data %>% 
          filter(apportionment_difference < 0,
                 !District %in% basic_aid_districts)
        
        plot_ly(type = 'scatter', mode = 'markers') %>%
              add_trace(
                name = "Districts Receiving More Money",
                x = districts_improved$apportionment_2017_18_grown_at_cola,
                y = districts_improved$apportionment_difference,
                marker = list(color= winners_color,
                              line = list(color = "black",
                                          width = 1)),
                text = districts_improved$District,
                hovertemplate = paste('<b>%{text}</b>',
                                      '<br><b>2017-18 Apportionment Grown At COLA</b>: %{x:$,.0f}<br>',
                                      '<br><b>SCFF Excess Apportionment</b>: %{y:$,.0f}<br>'),
                showlegend = T
              ) %>%
              add_trace(
                name =  "Basic Aid Districts",
                x = districts_basic_aid$apportionment_2017_18_grown_at_cola,
                y = districts_basic_aid$apportionment_difference,
                marker = list(color="white",
                              line = list(color = "black",
                                          width = 1)),
                text = districts_basic_aid$District,
                hovertemplate = paste('<b>%{text}</b>',
                                      '<br><b>2017-18 Apportionment Grown At COLA</b>: %{x:$,.0f}<br>',
                                      '<br><b>SCFF Excess Apportionment</b>: %{y:$,.0f}<br>'),
                showlegend = T
              ) %>%
              add_trace(
                name = "Districts Receiving Less Money",
                x = districts_harmed$apportionment_2017_18_grown_at_cola,
                y = districts_harmed$apportionment_difference,
                marker = list(color=losers_color,
                              line = list(color = "black",
                                          width = 1)),
                text = districts_harmed$District,
                hovertemplate = paste('<b>%{text}</b>',
                                      '<br><b>2017-18 Apportionment Grown At COLA</b>: %{x:$,.0f}<br>',
                                      '<br><b>SCFF Excess Apportionment</b>: %{y:$,.0f}<br>'),
                showlegend = T
              ) %>%
              layout(
                xaxis = list(
                  zeroline = F,
                  title = "2017-18 Apportionment Grown At COLA to 2019-20"
                ),
                yaxis = list(
                  # hoverformat = '.2f',
                  title = "SCFF Excess Apportionment" 
                )
              )
})
    
   ## Generate Bar Chart ----
    output$apportionment_bar <- renderPlotly({
      if(input$new_money_old_money == F){## Total Monies
          plot_data <- TotalMoney.dataInput() 
    
          plot_data <- plot_data %>% 
            mutate(scff_apportionment_2019_20 = base_allocation + supplemental_allocation + success_allocation) %>%
            mutate(scff_apportionment = scff_apportionment_2019_20 - (apportionment_2017_18*(1+(cola_2017_18)/100)*(1+(cola_2018_19)/100))
                   ,apportionment_2017_18_grown_at_cola = apportionment_2017_18*(1+(cola_2017_18)/100)*(1+(cola_2018_19)/100))%>% 
            arrange(desc(scff_apportionment))%>% 
            mutate(scff_apportionment_positive = if_else(scff_apportionment>=0 & !District %in% basic_aid_districts, scff_apportionment, NA_real_),
                   scff_apportionment_negative = if_else(scff_apportionment<0 & !District %in% basic_aid_districts, scff_apportionment, NA_real_),
                   scff_apportionment_basic_aid = if_else(District %in% basic_aid_districts, scff_apportionment, NA_real_))
                                            
                                          
      }else{## NEW Monies
          plot_data <- NewMoney.dataInput() 
    
          plot_data <- plot_data %>%   
            mutate(scff_apportionment = scff_apportionment_2019_20 #+ (apportionment_2017_18*(1+(cola_2017_18)/100)*(1+(cola_2018_19)/100))
                   ,apportionment_2017_18_grown_at_cola = apportionment_2017_18*(1+(cola_2017_18)/100)*(1+(cola_2018_19)/100)) %>% 
            arrange(desc(scff_apportionment)) %>% 
            mutate(scff_apportionment_positive = if_else(scff_apportionment>=0 & !District %in% basic_aid_districts, scff_apportionment, NA_real_),
                   scff_apportionment_negative = if_else(scff_apportionment<0 & !District %in% basic_aid_districts, scff_apportionment, NA_real_),
                   scff_apportionment_basic_aid = if_else(District %in% basic_aid_districts, scff_apportionment, NA_real_))
        }     
          
            plot_data$District <- factor(plot_data$District, 
                                              levels = unique(plot_data$District)[order(plot_data$scff_apportionment, decreasing = T)])
            plot_ly(plot_data, x =~District, y =~scff_apportionment_positive
                  ,type='bar' ,mode='markers', name='Districts Receiving More Money',  marker=list(color = winners_color
                                                                                                   ,line = list(color = "black", width = 1))) %>% 
          add_trace(y =~scff_apportionment_negative, name="Districts Receiving Less Money", marker=list(color = losers_color
                                                                                                        ,line = list(color = "black", width =1))) %>% 
          add_trace(y =~scff_apportionment_basic_aid, name="Basic Aid Districts", marker=list(color = "white"
                                                                                              ,line = list(color = "black", width = 1))) %>% 
          layout(
            xaxis = list(
              zeroline = F,
              title = ""
            ),
            yaxis = list(
              # hoverformat = '.2f',
              title = "SCFF Excess Apportionment" 
            ),
            showlegend = FALSE
          )
})
    
   #APPORTIONMENT PER FTES -----
   ## Generates per FTES Bar Chart ----
    output$per_ftes_bar <- renderPlotly({
       # if(input$new_money_old_money == F){ ## Total Monies
           plot_data <- TotalMoney.dataInput() 
    
           plot_data <- plot_data %>%                              
              mutate(scff_apportionment_2019_20 = base_allocation + supplemental_allocation + success_allocation) %>%
              mutate(per_ftes_apportionment = ((scff_apportionment_2019_20 #- (apportionment_2017_18*(1+(cola_2017_18)/100)*(1+(cola_2018_19)/100))
                                                ) / 
                                              (ftes_non_credit+cdcp+ftes_credit+special_admits_ftes_credit)
                                              )
                     ,apportionment_2017_18_grown_at_cola = apportionment_2017_18*(1+(cola_2017_18)/100)*(1+(cola_2018_19)/100))%>% 
              arrange(desc(per_ftes_apportionment))
                                          
        # }else{## NEW Monies
           plot_data_new_money <- NewMoney.dataInput() 
    
           plot_data_joined<- plot_data_new_money %>%                                
              mutate(per_ftes_apportionment_new_money = ((scff_apportionment_2019_20 + (apportionment_2017_18*(1+(cola_2017_18)/100)*(1+(cola_2018_19)/100))
                                                ) / 
                                              (ftes_non_credit+cdcp+ftes_credit+special_admits_ftes_credit)
                                              )
                     ,apportionment_2017_18_grown_at_cola = apportionment_2017_18*(1+(cola_2017_18)/100)*(1+(cola_2018_19)/100))%>% 
              arrange(desc(per_ftes_apportionment_new_money)) %>% 
             select(District, per_ftes_apportionment_new_money) %>% 
             right_join(plot_data, by = "District")
  # }     
    
           
            if(input$new_money_old_money == F){## Total Monies 
              plot_data_joined$District <- factor(plot_data_joined$District, 
                                      levels = unique(plot_data_joined$District)[order(plot_data_joined$per_ftes_apportionment, decreasing = T)])
            }else{## New Monies
              plot_data_joined$District <- factor(plot_data_joined$District, 
                                      levels = unique(plot_data_joined$District)[order(plot_data_joined$per_ftes_apportionment_new_money, decreasing = T)])
            }     
    
    plot_ly(plot_data_joined, x= ~District ,y = ~per_ftes_apportionment,type = 'bar',mode = 'markers', name="Total Money", 
            marker= list(color = total_money_color_dynamic())) %>% 
      add_trace(y = ~per_ftes_apportionment_new_money, name = "New Money",
                marker= list(color = new_money_color_dynamic())) %>% 
      layout(barmode = 'group') %>% 
      layout(
            xaxis = list(
              zeroline = F,
              title = ""
            ),
            yaxis = list(
              # hoverformat = '.2f',
              title = "Per FTES Apportionment" 
            ),
            showlegend = FALSE
          )
})
   ## Generates per FTES box plots ----
    output$per_ftes_box_plots <- renderPlotly({
      
      total_money_plot_data <- TotalMoney.dataInput()
      new_money_plot_data <- NewMoney.dataInput()
      
      plot_data <- total_money_plot_data %>% 
        mutate(scff_apportionment_2019_20 = base_allocation + supplemental_allocation + success_allocation) %>%
              mutate(per_ftes_apportionment = ((scff_apportionment_2019_20 #- (apportionment_2017_18*(1+(cola_2017_18)/100)*(1+(cola_2018_19)/100))
                                                ) / 
                                              (ftes_non_credit+cdcp+ftes_credit+special_admits_ftes_credit)
                                              )
                     ,apportionment_2017_18_grown_at_cola = apportionment_2017_18*(1+(cola_2017_18)/100)*(1+(cola_2018_19)/100)
                     ,formula_type = "Total Money") %>% 
        bind_rows(new_money_plot_data %>%
              mutate(per_ftes_apportionment = ((scff_apportionment_2019_20 + (apportionment_2017_18*(1+(cola_2017_18)/100)*(1+(cola_2018_19)/100))
                                                ) /
                                              (ftes_non_credit+cdcp+ftes_credit+special_admits_ftes_credit)
                                              )
                     ,apportionment_2017_18_grown_at_cola = apportionment_2017_18*(1+(cola_2017_18)/100)*(1+(cola_2018_19)/100)
                     ,formula_type = "New Money")
        )
      
      plot_data$formula_type <- factor(plot_data$formula_type, 
                                      levels = c("Total Money", "New Money"))
      
      box_plot <-  plot_ly(plot_data, y=~per_ftes_apportionment, color=~formula_type, colors = c(total_money_color, new_money_color), type="box"
                           ,boxpoints = "all", jitter = 0.3, pointpos = -1.8
                           ,hoverinfo = "text" 
                           ,text = ~paste('District: ', District
                                          ,'\nPer FTES Apportionment: $', format(round(per_ftes_apportionment,0), big.mark = ",", trim = T)
                                          )
                           ) %>% 
        layout(
            xaxis = list(
              zeroline = F,
              title = ""
            ),
            yaxis = list(
              # hoverformat = '.2f',
              title = "Per FTES Apportionment" 
            )
          )
        
        
        # ggplot(aes(x=formula_type, y=per_ftes_apportionment))+
        # geom_boxplot() %>% 
        # plotly()
      
      box_plot
      
      })
    
    
  
  # YOY CHANGE
   ## Generates YoY Change Bar
  output$yoy_change_bar <- renderPlotly({
     # if(input$new_money_old_money == F){ ## Total Monies
           plot_data <- TotalMoney.dataInput() 
    
           plot_data <- plot_data %>%                              
              mutate(scff_apportionment_2019_20 = case_when(District %in% basic_aid_districts ~ base_allocation + supplemental_allocation + success_allocation,
                                        apportionment_2017_18*(1+(cola_2017_18)/100)*(1+(cola_2018_19)/100) > base_allocation + supplemental_allocation + success_allocation~
                                          apportionment_2017_18*(1+(cola_2017_18)/100)*(1+(cola_2018_19)/100),
                                        TRUE ~ base_allocation + supplemental_allocation + success_allocation),
              yoy_apportionment_change_total = 
                       scff_apportionment_2019_20 / (apportionment_2017_18*(1+(cola_2017_18)/100))-1)%>% 
              arrange(desc(yoy_apportionment_change_total))
                                          
        # }else{## NEW Monies
           plot_data_new_money <- NewMoney.dataInput() 
    
           plot_data_joined<- plot_data_new_money %>%                                
              mutate(yoy_apportionment_change_new = ((scff_apportionment_2019_20 + (apportionment_2017_18*(1+(cola_2017_18)/100)*(1+(cola_2018_19)/100))
                                                ) / 
                                              (apportionment_2017_18*(1+(cola_2017_18)/100)))-1)%>% 
              arrange(desc(yoy_apportionment_change_new)) %>% 
             select(District, yoy_apportionment_change_new) %>% 
             right_join(plot_data, by = "District")
  # }     
    
           
            if(input$new_money_old_money == F){## Total Monies 
              plot_data_joined$District <- factor(plot_data_joined$District, 
                                      levels = unique(plot_data_joined$District)[order(plot_data_joined$yoy_apportionment_change_total, decreasing = T)])
            }else{## New Monies
              plot_data_joined$District <- factor(plot_data_joined$District, 
                                      levels = unique(plot_data_joined$District)[order(plot_data_joined$yoy_apportionment_change_new, decreasing = T)])
            }     
    
    plot <- plot_ly(plot_data_joined, x= ~District ,y = ~yoy_apportionment_change_total,type = 'bar',orientation = 'v', mode = 'markers', name="Total Money", 
            marker= list(color = total_money_color_dynamic())) %>% 
      add_trace(y = ~yoy_apportionment_change_new, name = "New Money",
                marker= list(color = new_money_color_dynamic())) %>% 
      layout(barmode = 'group') %>% 
      layout(
        xaxis = list(
          # tickformat = "%",
          # title = "YoY Change"
          zeroline = F,
          title = ""
        ),
        yaxis = list(
          # zeroline = F,
          # title = "",
          # list(tickfont = list(size = 8))
          tickformat = "%",
          title = "YoY Change"
        )
        # ,showlegend = FALSE
      )
    
    plot
  })
  
  }

```



```{r message=FALSE, warning=FALSE, include=FALSE}

shinyApp(ui, server, options = list(launch.browser=T))

```
```{r}
library(plotly)
set.seed(2017)
x <- seq(1:10)
y <- x + rnorm(10)
plot_ly(
    x = ~x,
    y = ~y + rnorm(10)) %>%
    layout(
        xaxis = list(tickfont = list(size = 15)), 
        yaxis = list(tickfont = list(size = 5)))
```

```{r}
# test_data <- tibble(
#   col_1 = c(1,2,3,4,5,6,7,8,9,10,2,4,6,8,10,12,14,16,18,20),
#   col_2 = c("g1","g1","g1","g1","g1","g1","g1","g1","g1","g1","g2","g2","g2","g2","g2","g2","g2","g2","g2","g2")
# ) %>% 
#   ggplot(aes(x = col_2, y = col_1)) +
#   geom_boxplot()
```

```{r}
# d <- tibble::tibble(
#   time = seq(as.Date("2016-01-01"), as.Date("2016-08-31"), by = "days"),
#   y = rnorm(seq_along(time))
#  )
#  
# plot_ly(d, x = ~time, y = ~y, type = "bar", orientation = "v") %>%
#   rangeslider(d$time[5], d$time[50])
```

